"""Stable provider contracts and shared provider boundary models for CreatorOS."""

from creatoros.providers.base import (
    LLMCapabilities,
    LLMRequest,
    LLMResponse,
    LLMUsage,
    ProviderCapability,
    ProviderInfo,
    ProviderRequestContext,
    ProviderResult,
    ProviderUsage,
)
from creatoros.providers.contracts import (
    AnalyticsProvider,
    ImageProvider,
    LLMProvider,
    Provider,
    PublishingProvider,
    SearchProvider,
    StorageProvider,
    TrendProvider,
    TTSProvider,
    VideoProvider,
    VoiceProvider,
)
from creatoros.providers.media import (
    GeneratedAudio,
    GeneratedImage,
    GeneratedVideo,
    ImageGenerationRequest,
    TTSGenerationRequest,
    VideoGenerationRequest,
)
from creatoros.providers.openai import (
    DEFAULT_OPENAI_IMAGE_MODEL,
    DEFAULT_OPENAI_IMAGE_PROVIDER_NAME,
    DEFAULT_OPENAI_MODEL,
    OpenAIImageProvider,
    OpenAILLMProvider,
    register_openai_image_provider,
    register_openai_provider,
)
from creatoros.providers.registry import (
    ProviderRegistry,
    create_provider_registry,
    get_provider_registry,
    resolve_default_image_provider,
    resolve_default_llm_provider,
    resolve_default_tts_provider,
    resolve_default_video_provider,
)

__all__ = [
    "DEFAULT_OPENAI_IMAGE_MODEL",
    "DEFAULT_OPENAI_IMAGE_PROVIDER_NAME",
    "DEFAULT_OPENAI_MODEL",
    "AnalyticsProvider",
    "GeneratedAudio",
    "GeneratedImage",
    "GeneratedVideo",
    "ImageGenerationRequest",
    "ImageProvider",
    "LLMCapabilities",
    "LLMProvider",
    "LLMRequest",
    "LLMResponse",
    "LLMUsage",
    "OpenAIImageProvider",
    "OpenAILLMProvider",
    "Provider",
    "ProviderCapability",
    "ProviderInfo",
    "ProviderRegistry",
    "ProviderRequestContext",
    "ProviderResult",
    "ProviderUsage",
    "PublishingProvider",
    "SearchProvider",
    "StorageProvider",
    "TTSGenerationRequest",
    "TTSProvider",
    "TrendProvider",
    "VideoGenerationRequest",
    "VideoProvider",
    "VoiceProvider",
    "create_provider_registry",
    "get_provider_registry",
    "register_openai_image_provider",
    "register_openai_provider",
    "resolve_default_image_provider",
    "resolve_default_llm_provider",
    "resolve_default_tts_provider",
    "resolve_default_video_provider",
]
